---
- name: Installation des serveurs pour le Portail invite
  hosts: serveur
  remote_user: root
  tasks: 
    - name: Installation de Apache2
       apt: name=apache2 state=latest
       shell: cd /var/www/html ; sudo git clone https://github.com/stage0144/Portailinvite ; cd Portailinvite ; sudo rm -r phpmailer ; sudo git clone https://github.com/PHPMailer/PHPMailer ; sudo mv PHPMailer phpmailer
       
    - name: Installation du serveur MySQL
       apt: name=mysql-server state=latest
       shell : sudo mysql -h localhost -u root < /home/charles/installation_portail_invite/bdd.sql

    - name: Installation de phpmyadmin
       apt: name=phpmyadmin state=latest
       
    - name: Installation du serveur Syslog
       apt: name=rsyslog state=latest
       
    - name: Installation de OpenSSL
       apt: name=openssl state=latest

    - name: Installation du serveur Radius
       apt: name=freeradius state=latest
       apt: name=freeradius-mysql state=latest
       apt: name=freeradius-utils state=latest
